-- INSERT
INSERT INTO ATTENDE (FIRST_NAME, LAST_NAME)
VALUES('Lucas', 'Monteiro');

SELECT * FROM ATTENDE;

INSERT INTO ATTENDE(FIRST_NAME, LAST_NAME, PHONE, EMAIL, VIP)
VALUES
('luca', 'Melo', 095482984, 'luca@gmail.com', 1),
('luca1', 'Melo', 195482984, 'luca1@gmail.com', 0),
('luca2', 'Melo', 295482984, 'luca2@gmail.com', 0),
('luca3', 'Melo', 395482984, 'luca3@gmail.com', 1);

--INSERT INTO ATTENDE(FIRST_NAME, LAST_NAME)
--SELECT FIRST_NAME, LAST_NAME
--FROM OTHER_TABLE;

INSERT INTO COMPANY(NAME, DESCRIPTION, PRIMARY_CONTACT_ATTENDEE_ID)
VALUES("Luca´s", 'teste', 3);

SELECT * FROM COMPANY;


--DELETE
DELETE FROM ATTENDE;

DELETE FROM ATTENDE
WHERE PHONE IS NULL
AND EMAIL IS NULL;
--A GOOD PRACTICE IS REPLACE 'DELETE' FOR 'SELECT', SO YOU CAN SEE WHAT WILL BE DELETED
SELECT * FROM ATTENDE
WHERE PHONE IS NULL
AND EMAIL IS NULL;


--TRUNCATE: REDEFINE THE AUTOINCREMENTS...


--UPDATE
UPDATE ATTENDE SET EMAIL = UPPER(EMAIL);

UPDATE ATTENDE SET FIRST_NAME = UPPER(FIRST_NAME),
LAST_NAME = UPPER(LAST_NAME),
VIP = 1
WHERE ATTENDE_ID IN (2,4);


--DROP TABLE
DROP TABLE ATTENDE;


